/**
 * Real Estate Module - Payment Types
 */

export type PaymentType = 'rent' | 'deposit' | 'fee' | 'maintenance' | 'utility';
export type PaymentStatus = 'pending' | 'paid' | 'overdue' | 'cancelled';
export type PaymentMethod = 'cash' | 'bank_transfer' | 'card' | 'check';

export interface ExtraCharge {
  name: string;
  amount: number;
  type?: string;
}

export interface Payment {
  id: string;
  tenantId: string;
  companyId: string;
  apartmentId: string;
  contractId?: string | null;
  type: PaymentType;
  amount: number;
  currency: string;
  dueDate: Date;
  paidDate?: Date | null;
  status: PaymentStatus;
  extraCharges?: ExtraCharge[] | null;
  totalAmount: number;
  paymentMethod?: PaymentMethod | null;
  receiptNumber?: string | null;
  notes?: string | null;
  isAutoGenerated: boolean;
  reminderSent: boolean;
  createdAt: Date;
  updatedAt: Date;
  apartment?: any;
  contract?: any;
}

export interface PaymentCreateInput {
  apartmentId: string;
  contractId?: string;
  type: PaymentType;
  amount: number;
  currency?: string;
  dueDate: Date;
  paidDate?: Date;
  status?: PaymentStatus;
  extraCharges?: ExtraCharge[];
  totalAmount: number;
  paymentMethod?: PaymentMethod;
  receiptNumber?: string;
  notes?: string;
  isAutoGenerated?: boolean;
  reminderSent?: boolean;
}

export interface PaymentUpdateInput extends Partial<Omit<PaymentCreateInput, 'totalAmount'>> {
  totalAmount?: number;
}

export interface PaymentListParams {
  page?: number;
  pageSize?: number;
  search?: string;
  apartmentId?: string;
  contractId?: string;
  type?: PaymentType;
  status?: PaymentStatus;
  dueDateFrom?: Date;
  dueDateTo?: Date;
}

