import { z } from 'zod';

export const paymentTypeSchema = z.enum(['rent', 'deposit', 'fee', 'maintenance', 'utility']);
export const paymentStatusSchema = z.enum(['pending', 'paid', 'overdue', 'cancelled']);
export const paymentMethodSchema = z.enum(['cash', 'bank_transfer', 'card', 'check']);

export const extraChargeSchema = z.object({
  name: z.string().min(1),
  amount: z.coerce.number().min(0),
  type: z.string().optional(),
});

export const paymentSchema = z.object({
  apartmentId: z.string().min(1, 'Apartment is required'),
  contractId: z.string().optional().nullable(),
  tenantRecordId: z.string().optional().nullable(),
  type: paymentTypeSchema,
  amount: z.coerce.number().min(0, 'Amount must be positive'),
  currency: z.preprocess((val) => val ?? 'TRY', z.string()),
  dueDate: z.coerce.date(),
  paidDate: z.coerce.date().optional().nullable(),
  status: paymentStatusSchema.default('pending'),
  extraCharges: z.array(extraChargeSchema).optional().nullable(),
  paymentMethod: paymentMethodSchema.optional().nullable(),
  receiptNumber: z.string().optional().nullable(),
  notes: z.string().optional().nullable(),
  isAutoGenerated: z.boolean().default(false),
  reminderSent: z.boolean().default(false),
});

export type PaymentFormValues = z.infer<typeof paymentSchema>;

// Create and update schemas
export const paymentCreateSchema = paymentSchema;
export const paymentUpdateSchema = paymentSchema.partial();

