'use client';

import { useEffect, useCallback } from 'react';
import {
  Stack,
  TextInput,
  Select,
  Grid,
  MultiSelect,
  Divider,
  Text,
} from '@mantine/core';
import { DateInput } from '@mantine/dates';
import { useParams } from 'next/navigation';
import { useTranslation } from '@/lib/i18n/client';
import { UseFormReturnType } from '@mantine/form';
import type { UserFormData } from '@/lib/schemas/user';
import classes from './WorkInfoTab.module.css';

interface WorkInfoTabProps {
  form: UseFormReturnType<UserFormData>;
  isEdit?: boolean;
}

// Generate employee ID from name: "John Doe" -> "EMP-JOHN-DOE-XXXX"
function generateEmployeeId(fullName: string): string {
  if (!fullName || fullName.trim().length === 0) return '';

  const slug = fullName
    .trim()
    .toUpperCase()
    .replace(/[^A-Z0-9\s]/g, '')
    .split(/\s+/)
    .slice(0, 2)
    .join('-');

  const randomSuffix = Math.random().toString(36).substring(2, 6).toUpperCase();
  return `EMP-${slug}-${randomSuffix}`;
}

export function WorkInfoTab({ form, isEdit = false }: WorkInfoTabProps) {
  const params = useParams();
  const locale = (params?.locale as string) || 'tr';
  const dayjsLocale = locale === 'tr' ? 'tr' : locale === 'de' ? 'de' : locale === 'ar' ? 'ar' : 'en';
  const { t } = useTranslation('modules/users');

  // Mock agencies - should come from API
  const agencies = [
    { value: '1', label: 'Stark Industries' },
    { value: '2', label: 'Wayne Enterprises' },
    { value: '3', label: 'Cyberdyne Systems' },
  ];

  // Departments based on modules
  const departments = [
    // Core/Management
    { value: 'Management', label: t('departments.management') },
    { value: 'IT', label: t('departments.it') },
    { value: 'HR', label: t('departments.hr') },
    { value: 'Finance', label: t('departments.finance') },
    // Module-based departments
    { value: 'RealEstate', label: t('departments.realEstate') },
    { value: 'Accounting', label: t('departments.accounting') },
    { value: 'Production', label: t('departments.production') },
    { value: 'Maintenance', label: t('departments.maintenance') },
    { value: 'Sales', label: t('departments.sales') },
    { value: 'Marketing', label: t('departments.marketing') },
    { value: 'Logistics', label: t('departments.logistics') },
    { value: 'CustomerService', label: t('departments.customerService') },
    { value: 'WebDevelopment', label: t('departments.webDevelopment') },
    { value: 'AI', label: t('departments.ai') },
    { value: 'Other', label: t('departments.other') },
  ];

  // Auto-generate employee ID from full name (only for new users)
  const fullName = form.values.personal?.fullName || '';
  const currentEmployeeId = form.values.work?.employeeId || '';

  const updateEmployeeId = useCallback(() => {
    if (!isEdit && fullName && !currentEmployeeId) {
      const newId = generateEmployeeId(fullName);
      form.setFieldValue('work.employeeId', newId);
    }
  }, [fullName, isEdit, currentEmployeeId, form]);

  useEffect(() => {
    // Generate ID when name changes (debounced effect)
    const timer = setTimeout(() => {
      updateEmployeeId();
    }, 500);
    return () => clearTimeout(timer);
  }, [updateEmployeeId]);

  return (
    <Stack gap="xl" p="xl" {...(classes.container ? { className: classes.container } : {})}>
      <div>
        <Text fw={600} size="lg">{t('form.work.title')}</Text>
        <Text size="sm" c="dimmed">{t('form.work.description')}</Text>
      </div>

      <Divider />

      <Grid gutter="md">
        {/* Row 1: Department, Position, Employee ID */}
        <Grid.Col span={{ base: 12, sm: 6, lg: 4 }}>
          <Select
            label={t('form.work.department')}
            placeholder={t('form.work.departmentPlaceholder')}
            data={departments}
            searchable
            clearable
            {...form.getInputProps('work.department')}
          />
        </Grid.Col>
        <Grid.Col span={{ base: 12, sm: 6, lg: 4 }}>
          <TextInput
            label={t('form.work.position')}
            placeholder={t('form.work.positionPlaceholder')}
            {...form.getInputProps('work.position')}
          />
        </Grid.Col>
        <Grid.Col span={{ base: 12, sm: 6, lg: 4 }}>
          <TextInput
            label={t('form.work.employeeId')}
            placeholder={t('form.work.employeeIdPlaceholder')}
            description={!isEdit ? t('form.work.employeeIdAutoGenerated') : undefined}
            readOnly={!isEdit}
            styles={!isEdit ? { input: { backgroundColor: 'var(--mantine-color-gray-1)', cursor: 'default' } } : undefined}
            {...form.getInputProps('work.employeeId')}
          />
        </Grid.Col>

        {/* Row 2: Hire Date, Manager, Role */}
        <Grid.Col span={{ base: 12, sm: 6, lg: 4 }}>
          <DateInput
            label={t('form.work.hireDate')}
            placeholder={t('form.work.hireDatePlaceholder')}
            locale={dayjsLocale}
            {...form.getInputProps('work.hireDate')}
          />
        </Grid.Col>
        <Grid.Col span={{ base: 12, sm: 6, lg: 4 }}>
          <TextInput
            label={t('form.work.manager')}
            placeholder={t('form.work.managerPlaceholder')}
            {...form.getInputProps('work.manager')}
          />
        </Grid.Col>
        <Grid.Col span={{ base: 12, sm: 6, lg: 4 }}>
          <Select
            label={t('form.work.role')}
            required
            data={[
              { value: 'SuperAdmin', label: 'Super Admin' },
              { value: 'AgencyUser', label: 'Agency User' },
              { value: 'ClientUser', label: 'Client User' },
            ]}
            {...form.getInputProps('work.role')}
          />
        </Grid.Col>

        {/* Row 3: Assign Agency (full width) */}
        <Grid.Col span={{ base: 12 }}>
          <MultiSelect
            label={t('form.work.assignAgency')}
            placeholder={t('form.work.assignAgencyPlaceholder')}
            data={agencies}
            {...form.getInputProps('work.agencyIds')}
          />
        </Grid.Col>
      </Grid>
    </Stack>
  );
}
