/**
 * Generate Payments Script
 * 
 * This script automatically generates monthly rent payments for active contracts.
 * Should be run monthly via cron job or scheduled task.
 * 
 * Usage:
 *   npm run payments:generate
 * 
 * Or via cron (run on 1st of each month):
 *   0 0 1 * * cd /path/to/project && npm run payments:generate
 */

import 'dotenv/config';
import { PrismaClient as CorePrismaClient } from '@prisma/core-client';
import { PrismaClient as TenantPrismaClient } from '@prisma/tenant-client';
import dayjs from 'dayjs';
import { getTenantConfig } from '../src/config/tenant.config';

// Initialize Prisma clients
const corePrisma = new CorePrismaClient({
  datasources: {
    db: {
      url: process.env.CORE_DATABASE_URL,
    },
  },
  log: process.env.NODE_ENV === 'development' ? ['error'] : ['error'],
});

// Cache for tenant Prisma clients
const tenantClientsCache = new Map<string, TenantPrismaClient>();

function getTenantPrisma(dbUrl: string): TenantPrismaClient {
  if (tenantClientsCache.has(dbUrl)) {
    return tenantClientsCache.get(dbUrl)!;
  }
  const client = new TenantPrismaClient({
    datasources: {
      db: {
        url: dbUrl,
      },
    },
    log: process.env.NODE_ENV === 'development' ? ['error'] : ['error'],
  });
  tenantClientsCache.set(dbUrl, client);
  return client;
}

async function generatePayments() {
  console.log('Starting payment generation process...');

  try {
    const config = getTenantConfig();
    // Get all active tenants
    const tenants = await corePrisma.tenant.findMany({
      where: { status: 'active' },
    });

    const targetMonth = dayjs().month() + 1; // Current month (1-12)
    const targetYear = dayjs().year();

    let totalGenerated = 0;
    let totalSkipped = 0;
    let totalErrors = 0;

    for (const tenant of tenants) {
      console.log(`Processing tenant: ${tenant.slug} (ID: ${tenant.id})`);
      try {
        const dbUrl = config.tenantDbTemplateUrl.replace('__DB_NAME__', tenant.currentDb) ||
          `postgresql://${process.env.PG_USER || 'postgres'}@${process.env.PG_HOST || 'localhost'}:${process.env.PG_PORT || '5432'}/${tenant.currentDb}?schema=public`;
        const tenantPrisma = getTenantPrisma(dbUrl);

        // Get companyId
        const firstCompany = await tenantPrisma.company.findFirst({
          select: { id: true },
          orderBy: { createdAt: 'asc' },
        });

        if (!firstCompany) {
          console.log(`  No company found for tenant ${tenant.slug}`);
          continue;
        }

        const companyId = firstCompany.id;

        // Find active contracts
        const activeContracts = await tenantPrisma.contract.findMany({
          where: {
            tenantId: tenant.id,
            status: 'active',
          },
          include: {
            apartment: {
              select: {
                id: true,
                unitNumber: true,
              },
            },
          },
        });

        let generated = 0;
        let skipped = 0;

        for (const contract of activeContracts) {
          try {
            // Skip if contract doesn't have paymentDay set
            if (!contract.paymentDay) {
              skipped++;
              continue;
            }

            // Calculate due date for this month
            const targetDate = dayjs().year(targetYear).month(targetMonth - 1);
            const daysInMonth = targetDate.daysInMonth();
            const paymentDay = Math.min(contract.paymentDay, daysInMonth);
            const dueDate = targetDate.date(paymentDay).startOf('day').toDate();

            // Check if payment already exists for this contract and month
            const existingPayment = await tenantPrisma.payment.findFirst({
              where: {
                tenantId: tenant.id,
                contractId: contract.id,
                type: 'rent',
                dueDate: {
                  gte: targetDate.startOf('month').toDate(),
                  lte: targetDate.endOf('month').toDate(),
                },
              },
            });

            if (existingPayment) {
              skipped++;
              continue;
            }

            // Create payment
            await tenantPrisma.payment.create({
              data: {
                tenantId: tenant.id,
                companyId: companyId,
                apartmentId: contract.apartmentId,
                contractId: contract.id,
                type: 'rent',
                amount: contract.rentAmount,
                currency: contract.currency || 'TRY',
                dueDate: dueDate,
                status: 'pending',
                totalAmount: contract.rentAmount,
                isAutoGenerated: true,
                reminderSent: false,
              },
            });

            generated++;
            console.log(`  Generated payment for contract: ${contract.contractNumber}`);
          } catch (innerError: any) {
            totalErrors++;
            console.error(`  Error generating payment for contract ${contract.id}:`, innerError);
          }
        }

        totalGenerated += generated;
        totalSkipped += skipped;
        console.log(`  Tenant ${tenant.slug}: Generated ${generated}, Skipped ${skipped}`);
      } catch (tenantError: any) {
        totalErrors++;
        console.error(`Error processing tenant ${tenant.slug}:`, tenantError);
      }
    }

    console.log(`Payment generation completed. Total generated: ${totalGenerated}, Total skipped: ${totalSkipped}, Total errors: ${totalErrors}`);
  } catch (error: any) {
    console.error('Fatal error in payment generation:', error);
  } finally {
    await corePrisma.$disconnect();
    for (const client of tenantClientsCache.values()) {
      await client.$disconnect();
    }
  }
}

// Run if called directly
if (require.main === module) {
  generatePayments();
}

export { generatePayments };








