'use client';

import { useEffect, useState } from 'react';
import { useForm } from '@mantine/form';
import {
  Paper,
  TextInput,
  Textarea,
  Button,
  Group,
  Stack,
  Grid,
  Select,
  NumberInput,
  Switch,
  Text,
  ActionIcon,
  Card,
  ThemeIcon,
  Anchor,
} from '@mantine/core';
import { DateInput } from '@mantine/dates';
import { notifications } from '@mantine/notifications';
import { IconArrowLeft, IconX, IconPlus, IconBuilding, IconHome, IconUser, IconMapPin } from '@tabler/icons-react';
import { useRouter } from 'next/navigation';
import { useCreatePayment, useUpdatePayment, usePayment } from '@/hooks/usePayments';
import { useApartments } from '@/hooks/useApartments';
import { useContracts } from '@/hooks/useContracts';
import { useTranslation } from '@/lib/i18n/client';
import { useCurrency } from '@/hooks/useCurrency';
import { CURRENCY_SELECT_OPTIONS } from '@/lib/constants/currency';
import type { PaymentType, PaymentStatus, PaymentMethod, ExtraCharge } from '@/modules/real-estate/types/payment';

interface PaymentFormProps {
  locale: string;
  paymentId?: string;
}

export function PaymentForm({ locale, paymentId }: PaymentFormProps) {
  const router = useRouter();
  const { t } = useTranslation('modules/real-estate');
  const { t: tGlobal } = useTranslation('global');
  const { currency: defaultCurrency } = useCurrency();
  const createPayment = useCreatePayment();
  const updatePayment = useUpdatePayment();
  const { data: paymentData, isLoading: isLoadingPayment } = usePayment(paymentId || '');
  const { data: apartmentsData } = useApartments({ page: 1, pageSize: 1000 });
  const { data: contractsData } = useContracts({ page: 1, pageSize: 1000 });

  const isEdit = !!paymentId;

  const [extraCharges, setExtraCharges] = useState<ExtraCharge[]>([]);
  const [currencyInitialized, setCurrencyInitialized] = useState(false);

  const form = useForm({
    initialValues: {
      apartmentId: '',
      contractId: null as string | null,
      type: 'rent' as PaymentType,
      amount: 0,
      currency: 'TRY',
      dueDate: null as Date | null,
      paidDate: null as Date | null,
      status: 'pending' as PaymentStatus,
      paymentMethod: null as PaymentMethod | null,
      receiptNumber: '' as string,
      notes: '' as string,
      isAutoGenerated: false,
      reminderSent: false,
    },
    validate: {
      apartmentId: (value) => (!value ? t('form.required') : null),
      amount: (value) => (value <= 0 ? t('form.amountRequired') : null),
      dueDate: (value) => (!value ? t('form.required') : null),
    },
  });

  // Load payment data for edit
  useEffect(() => {
    if (isEdit && paymentData) {
      form.setValues({
        apartmentId: paymentData.apartmentId,
        contractId: paymentData.contractId || null,
        type: paymentData.type,
        amount: Number(paymentData.amount),
        currency: paymentData.currency,
        dueDate: paymentData.dueDate ? new Date(paymentData.dueDate) : null,
        paidDate: paymentData.paidDate ? new Date(paymentData.paidDate) : null,
        status: paymentData.status,
        paymentMethod: paymentData.paymentMethod || null,
        receiptNumber: paymentData.receiptNumber || '',
        notes: paymentData.notes || '',
        isAutoGenerated: paymentData.isAutoGenerated,
        reminderSent: paymentData.reminderSent,
      });
      if (paymentData.extraCharges && Array.isArray(paymentData.extraCharges)) {
        setExtraCharges(paymentData.extraCharges);
      }
      setCurrencyInitialized(true);
    }
  }, [paymentData, isEdit]);

  // Set default currency from GeneralSettings for new payments
  useEffect(() => {
    if (!isEdit && !currencyInitialized && defaultCurrency) {
      form.setFieldValue('currency', defaultCurrency);
      setCurrencyInitialized(true);
    }
  }, [isEdit, currencyInitialized, defaultCurrency]);

  const addExtraCharge = () => {
    setExtraCharges([...extraCharges, { name: '', amount: 0 }]);
  };

  const removeExtraCharge = (index: number) => {
    setExtraCharges(extraCharges.filter((_, i) => i !== index));
  };

  const updateExtraCharge = (index: number, field: keyof ExtraCharge, value: string | number) => {
    const updated = [...extraCharges];
    const current = updated[index];
    if (current) {
      updated[index] = { 
        ...current,
        [field]: value 
      };
      setExtraCharges(updated);
    }
  };

  const calculateTotalAmount = () => {
    const baseAmount = form.values.amount || 0;
    const extraTotal = extraCharges.reduce((sum, charge) => sum + (charge.amount || 0), 0);
    return baseAmount + extraTotal;
  };

  const handleSubmit = async (values: typeof form.values) => {
    try {
      const totalAmount = calculateTotalAmount();
      const paymentData: any = {
        ...values,
        totalAmount,
        extraCharges: extraCharges.length > 0 ? extraCharges : undefined,
      };

      if (isEdit && paymentId) {
        await updatePayment.mutateAsync({ id: paymentId, input: paymentData as any });
        notifications.show({
          title: t('messages.success'),
          message: t('messages.updateSuccess'),
          color: 'green',
        });
      } else {
        await createPayment.mutateAsync(paymentData);
        notifications.show({
          title: t('messages.success'),
          message: t('messages.createSuccess'),
          color: 'green',
        });
      }
      router.push(`/${locale}/modules/real-estate/payments`);
    } catch (error) {
      notifications.show({
        title: t('messages.error'),
        message: error instanceof Error ? error.message : t('messages.createError'),
        color: 'red',
      });
    }
  };

  if (isEdit && isLoadingPayment) {
    return <Text>{tGlobal('common.loading')}</Text>;
  }

  return (
    <Paper shadow="xs" p="md">
      <form onSubmit={form.onSubmit(handleSubmit)}>
        <Stack gap="md">
          <Group justify="space-between">
            <Button
              variant="subtle"
              leftSection={<IconArrowLeft size={18} />}
              onClick={() => router.push(`/${locale}/modules/real-estate/payments`)}
            >
              {tGlobal('common.back')}
            </Button>
            <Text size="lg" fw={500}>
              {isEdit ? t('payments.edit') : t('payments.create')}
            </Text>
          </Group>

          {/* Hierarchical Info Card - Show related property/apartment/tenant when editing */}
          {isEdit && paymentData && (
            (() => {
              const apartment = (paymentData as any).apartment;
              const contract = (paymentData as any).contract;
              const property = apartment?.property;
              const tenant = contract?.tenantRecord;

              if (!apartment && !property && !tenant) return null;

              return (
                <Card withBorder p="sm" radius="md" bg="var(--mantine-color-default-hover)">
                  <Group gap="lg" wrap="wrap" align="flex-start">
                    {/* Property */}
                    {property && (
                      <Group gap="xs" align="flex-start">
                        <ThemeIcon variant="light" color="blue" size="sm">
                          <IconBuilding size={14} />
                        </ThemeIcon>
                        <Stack gap={0}>
                          <Text size="xs" c="dimmed">{t('properties.title')}</Text>
                          <Anchor
                            href={`/${locale}/modules/real-estate/properties/${property.id}`}
                            size="sm"
                            fw={500}
                          >
                            {property.name}
                          </Anchor>
                          {(property.address || property.city) && (
                            <Group gap={4}>
                              <IconMapPin size={10} style={{ opacity: 0.6 }} />
                              <Text size="xs" c="dimmed">
                                {[property.address, property.city].filter(Boolean).join(', ')}
                              </Text>
                            </Group>
                          )}
                        </Stack>
                      </Group>
                    )}

                    {/* Apartment */}
                    {apartment && (
                      <Group gap="xs" align="flex-start">
                        <ThemeIcon variant="light" color="green" size="sm">
                          <IconHome size={14} />
                        </ThemeIcon>
                        <Stack gap={0}>
                          <Text size="xs" c="dimmed">{t('apartments.title')}</Text>
                          <Anchor
                            href={`/${locale}/modules/real-estate/apartments/${apartment.id}`}
                            size="sm"
                            fw={500}
                          >
                            {t('apartments.form.unit')} {apartment.unitNumber}
                          </Anchor>
                        </Stack>
                      </Group>
                    )}

                    {/* Tenant */}
                    {tenant && (
                      <Group gap="xs" align="flex-start">
                        <ThemeIcon variant="light" color="orange" size="sm">
                          <IconUser size={14} />
                        </ThemeIcon>
                        <Stack gap={0}>
                          <Text size="xs" c="dimmed">{t('tenants.title')}</Text>
                          <Anchor
                            href={`/${locale}/modules/real-estate/tenants/${tenant.id}`}
                            size="sm"
                            fw={500}
                          >
                            {tenant.tenantType === 'company' && tenant.companyName
                              ? tenant.companyName
                              : [tenant.firstName, tenant.lastName].filter(Boolean).join(' ') || tGlobal('common.noData')}
                          </Anchor>
                          {(tenant.email || tenant.phone) && (
                            <Text size="xs" c="dimmed">
                              {[tenant.email, tenant.phone].filter(Boolean).join(' • ')}
                            </Text>
                          )}
                        </Stack>
                      </Group>
                    )}
                  </Group>
                </Card>
              );
            })()
          )}

          <Grid>
            <Grid.Col span={{ base: 12, md: 6 }}>
              <Select
                label={t('form.apartment')}
                placeholder={t('form.selectApartment')}
                data={apartmentsData?.apartments.map(a => ({ value: a.id, label: a.unitNumber })) || []}
                required
                {...form.getInputProps('apartmentId')}
              />
            </Grid.Col>

            <Grid.Col span={{ base: 12, md: 6 }}>
              <Select
                label={t('form.contract')}
                placeholder={t('form.selectContract')}
                data={[
                  { value: '', label: t('form.none') },
                  ...(contractsData?.contracts.map(c => ({ value: c.id, label: c.contractNumber })) || []),
                ]}
                clearable
                {...form.getInputProps('contractId')}
                onChange={(value) => form.setFieldValue('contractId', value || null)}
              />
            </Grid.Col>

            <Grid.Col span={{ base: 12, md: 6 }}>
              <Select
                label={t('form.type')}
                data={[
                  { value: 'rent', label: t('payments.types.rent') },
                  { value: 'deposit', label: t('payments.types.deposit') },
                  { value: 'fee', label: t('payments.types.fee') },
                  { value: 'maintenance', label: t('payments.types.maintenance') },
                  { value: 'utility', label: t('payments.types.utility') },
                ]}
                required
                {...form.getInputProps('type')}
              />
            </Grid.Col>

            <Grid.Col span={{ base: 12, md: 6 }}>
              <NumberInput
                label={t('form.amount')}
                placeholder={t('form.enterAmount')}
                required
                min={0}
                decimalScale={2}
                fixedDecimalScale
                {...form.getInputProps('amount')}
              />
            </Grid.Col>

            <Grid.Col span={{ base: 12, md: 6 }}>
              <Select
                label={t('form.currency')}
                data={CURRENCY_SELECT_OPTIONS}
                {...form.getInputProps('currency')}
              />
            </Grid.Col>

            <Grid.Col span={{ base: 12, md: 6 }}>
              <DateInput
                label={t('form.dueDate')}
                placeholder={t('form.selectDate')}
                required
                locale={locale === 'tr' ? 'tr' : locale === 'de' ? 'de' : locale === 'ar' ? 'ar' : 'en'}
                {...form.getInputProps('dueDate')}
              />
            </Grid.Col>

            <Grid.Col span={{ base: 12, md: 6 }}>
              <DateInput
                label={t('form.paidDate')}
                placeholder={t('form.selectDate')}
                locale={locale === 'tr' ? 'tr' : locale === 'de' ? 'de' : locale === 'ar' ? 'ar' : 'en'}
                {...form.getInputProps('paidDate')}
              />
            </Grid.Col>

            <Grid.Col span={{ base: 12, md: 6 }}>
              <Select
                label={t('form.status')}
                data={[
                  { value: 'pending', label: t('payments.status.pending') },
                  { value: 'paid', label: t('payments.status.paid') },
                  { value: 'overdue', label: t('payments.status.overdue') },
                  { value: 'cancelled', label: t('payments.status.cancelled') },
                ]}
                {...form.getInputProps('status')}
              />
            </Grid.Col>

            <Grid.Col span={{ base: 12, md: 6 }}>
              <Select
                label={t('form.paymentMethod')}
                placeholder={t('form.selectPaymentMethod')}
                data={[
                  { value: 'cash', label: t('payments.methods.cash') },
                  { value: 'bank_transfer', label: t('payments.methods.bankTransfer') },
                  { value: 'card', label: t('payments.methods.card') },
                  { value: 'check', label: t('payments.methods.check') },
                ]}
                clearable
                {...form.getInputProps('paymentMethod')}
                onChange={(value) => form.setFieldValue('paymentMethod', value as PaymentMethod || null)}
              />
            </Grid.Col>

            <Grid.Col span={{ base: 12, md: 6 }}>
              <TextInput
                label={t('form.receiptNumber')}
                placeholder={t('form.enterReceiptNumber')}
                {...form.getInputProps('receiptNumber')}
              />
            </Grid.Col>

            <Grid.Col span={12}>
              <Stack gap="xs">
                <Group justify="space-between">
                  <Text size="sm" fw={500}>
                    {t('form.extraCharges')}
                  </Text>
                  <Button
                    size="xs"
                    variant="light"
                    leftSection={<IconPlus size={16} />}
                    onClick={addExtraCharge}
                  >
                    {t('form.addExtraCharge')}
                  </Button>
                </Group>
                {extraCharges.map((charge, index) => (
                  <Group key={index} gap="xs">
                    <TextInput
                      placeholder={t('form.chargeName')}
                      value={charge.name}
                      onChange={(e) => updateExtraCharge(index, 'name', e.target.value)}
                      style={{ flex: 1 }}
                    />
                    <NumberInput
                      placeholder={t('form.amount')}
                      value={charge.amount}
                      onChange={(value) => updateExtraCharge(index, 'amount', Number(value) || 0)}
                      min={0}
                      decimalScale={2}
                      fixedDecimalScale
                      style={{ width: 150 }}
                    />
                    <ActionIcon
                      color="red"
                      variant="subtle"
                      onClick={() => removeExtraCharge(index)}
                    >
                      <IconX size={16} />
                    </ActionIcon>
                  </Group>
                ))}
                {extraCharges.length > 0 && (
                  <Text size="sm" c="dimmed">
                    {t('form.totalAmount')}: {calculateTotalAmount().toLocaleString('tr-TR', {
                      style: 'currency',
                      currency: form.values.currency || 'TRY',
                    })}
                  </Text>
                )}
              </Stack>
            </Grid.Col>

            <Grid.Col span={12}>
              <Textarea
                label={t('form.notes')}
                placeholder={t('form.enterNotes')}
                rows={3}
                {...form.getInputProps('notes')}
              />
            </Grid.Col>

            {isEdit && (
              <>
                <Grid.Col span={{ base: 12, md: 6 }}>
                  <Switch
                    label={t('form.isAutoGenerated')}
                    {...form.getInputProps('isAutoGenerated', { type: 'checkbox' })}
                    disabled
                  />
                </Grid.Col>
                <Grid.Col span={{ base: 12, md: 6 }}>
                  <Switch
                    label={t('form.reminderSent')}
                    {...form.getInputProps('reminderSent', { type: 'checkbox' })}
                  />
                </Grid.Col>
              </>
            )}
          </Grid>

          <Group justify="flex-end">
            <Button type="submit" loading={createPayment.isPending || updatePayment.isPending}>
              {isEdit ? t('actions.update') : t('actions.create')}
            </Button>
          </Group>
        </Stack>
      </form>
    </Paper>
  );
}

