-- CreateTable
CREATE TABLE "Property" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "code" TEXT,
    "address" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "district" TEXT,
    "neighborhood" TEXT,
    "street" TEXT,
    "buildingNo" TEXT,
    "postalCode" TEXT,
    "country" TEXT NOT NULL DEFAULT 'TR',
    "latitude" DECIMAL(10,8),
    "longitude" DECIMAL(11,8),
    "totalUnits" INTEGER NOT NULL DEFAULT 0,
    "managerId" TEXT,
    "managerUserId" TEXT,
    "monthlyFee" DECIMAL(10,2),
    "paymentDay" INTEGER,
    "description" TEXT,
    "images" TEXT[],
    "documents" TEXT[],
    "metadata" JSONB,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Property_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Apartment" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "propertyId" TEXT NOT NULL,
    "unitNumber" TEXT NOT NULL,
    "floor" INTEGER,
    "block" TEXT,
    "area" DECIMAL(10,2) NOT NULL,
    "roomCount" INTEGER NOT NULL,
    "livingRoom" BOOLEAN NOT NULL DEFAULT true,
    "bathroomCount" INTEGER NOT NULL DEFAULT 1,
    "balcony" BOOLEAN NOT NULL DEFAULT false,
    "ownerId" TEXT,
    "ownerType" TEXT,
    "ownershipType" TEXT,
    "status" TEXT NOT NULL DEFAULT 'empty',
    "deliveryDate" TIMESTAMP(3),
    "rentPrice" DECIMAL(10,2),
    "salePrice" DECIMAL(10,2),
    "inventory" JSONB,
    "keys" JSONB,
    "description" TEXT,
    "images" TEXT[],
    "documents" TEXT[],
    "metadata" JSONB,
    "qrCode" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Apartment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Tenant" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "userId" TEXT,
    "contactId" TEXT,
    "tenantNumber" TEXT,
    "moveInDate" TIMESTAMP(3),
    "moveOutDate" TIMESTAMP(3),
    "paymentScore" DECIMAL(5,2) DEFAULT 100,
    "contactScore" DECIMAL(5,2) DEFAULT 100,
    "maintenanceScore" DECIMAL(5,2) DEFAULT 100,
    "overallScore" DECIMAL(5,2) DEFAULT 100,
    "notes" TEXT,
    "analysis" JSONB,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Tenant_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Contract" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "apartmentId" TEXT NOT NULL,
    "tenantRecordId" TEXT NOT NULL,
    "contractNumber" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3),
    "renewalDate" TIMESTAMP(3),
    "rentAmount" DECIMAL(10,2) NOT NULL,
    "deposit" DECIMAL(10,2),
    "currency" TEXT NOT NULL DEFAULT 'TRY',
    "paymentType" TEXT,
    "paymentDay" INTEGER,
    "autoRenewal" BOOLEAN NOT NULL DEFAULT false,
    "renewalNoticeDays" INTEGER DEFAULT 30,
    "increaseRate" DECIMAL(5,4),
    "status" TEXT NOT NULL DEFAULT 'active',
    "documents" TEXT[],
    "terms" TEXT,
    "notes" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Contract_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Payment" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "apartmentId" TEXT NOT NULL,
    "contractId" TEXT,
    "type" TEXT NOT NULL,
    "amount" DECIMAL(10,2) NOT NULL,
    "currency" TEXT NOT NULL DEFAULT 'TRY',
    "dueDate" TIMESTAMP(3) NOT NULL,
    "paidDate" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'pending',
    "extraCharges" JSONB,
    "totalAmount" DECIMAL(10,2) NOT NULL,
    "paymentMethod" TEXT,
    "receiptNumber" TEXT,
    "notes" TEXT,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "reminderSent" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Payment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Appointment" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "apartmentId" TEXT,
    "type" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "startDate" TIMESTAMP(3) NOT NULL,
    "endDate" TIMESTAMP(3) NOT NULL,
    "duration" INTEGER,
    "staffIds" TEXT[],
    "externalParticipants" JSONB,
    "status" TEXT NOT NULL DEFAULT 'scheduled',
    "followUpRequired" BOOLEAN NOT NULL DEFAULT false,
    "followUpDate" TIMESTAMP(3),
    "followUpNotes" TEXT,
    "result" JSONB,
    "rating" INTEGER,
    "interestLevel" TEXT,
    "location" TEXT,
    "notes" TEXT,
    "calendarEventId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Appointment_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RealEstateStaff" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "userId" TEXT,
    "name" TEXT NOT NULL,
    "email" TEXT,
    "phone" TEXT,
    "staffType" TEXT NOT NULL,
    "role" TEXT NOT NULL,
    "permissions" JSONB,
    "propertyIds" TEXT[],
    "apartmentIds" TEXT[],
    "assignedUnits" INTEGER NOT NULL DEFAULT 0,
    "collectionRate" DECIMAL(5,2),
    "averageVacancyDays" DECIMAL(10,2),
    "customerSatisfaction" DECIMAL(5,2),
    "notes" TEXT,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RealEstateStaff_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "PropertyStaff" (
    "id" TEXT NOT NULL,
    "propertyId" TEXT NOT NULL,
    "staffId" TEXT NOT NULL,
    "role" TEXT,
    "startDate" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "endDate" TIMESTAMP(3),
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "PropertyStaff_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "RealEstateMaintenanceRecord" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "apartmentId" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT NOT NULL DEFAULT 'scheduled',
    "scheduledDate" TIMESTAMP(3) NOT NULL,
    "startDate" TIMESTAMP(3),
    "endDate" TIMESTAMP(3),
    "assignedStaffId" TEXT,
    "performedByStaffId" TEXT,
    "estimatedCost" DECIMAL(10,2),
    "actualCost" DECIMAL(10,2),
    "documents" TEXT[],
    "photos" TEXT[],
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "RealEstateMaintenanceRecord_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EmailTemplate" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "companyId" TEXT,
    "name" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "subject" TEXT NOT NULL,
    "htmlContent" TEXT NOT NULL,
    "textContent" TEXT,
    "variables" JSONB,
    "isDefault" BOOLEAN NOT NULL DEFAULT false,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EmailTemplate_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "EmailCampaign" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "templateId" TEXT NOT NULL,
    "apartmentId" TEXT,
    "name" TEXT NOT NULL,
    "recipients" JSONB NOT NULL,
    "recipientCount" INTEGER NOT NULL DEFAULT 0,
    "customContent" JSONB,
    "scheduledAt" TIMESTAMP(3),
    "sentAt" TIMESTAMP(3),
    "status" TEXT NOT NULL DEFAULT 'draft',
    "sentCount" INTEGER NOT NULL DEFAULT 0,
    "openedCount" INTEGER NOT NULL DEFAULT 0,
    "clickedCount" INTEGER NOT NULL DEFAULT 0,
    "conversionCount" INTEGER NOT NULL DEFAULT 0,
    "notes" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "EmailCampaign_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "AgreementReport" (
    "id" TEXT NOT NULL,
    "tenantId" TEXT NOT NULL,
    "companyId" TEXT NOT NULL,
    "appointmentId" TEXT,
    "type" TEXT NOT NULL,
    "apartmentId" TEXT NOT NULL,
    "contractId" TEXT,
    "agreementStatus" TEXT NOT NULL,
    "rentAmount" DECIMAL(10,2),
    "deposit" DECIMAL(10,2),
    "deliveryDate" TIMESTAMP(3),
    "contractDate" TIMESTAMP(3),
    "specialTerms" TEXT,
    "nextSteps" TEXT,
    "recipients" JSONB NOT NULL,
    "attachments" TEXT[],
    "status" TEXT NOT NULL DEFAULT 'draft',
    "sentAt" TIMESTAMP(3),
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "AgreementReport_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "Property_tenantId_companyId_idx" ON "Property"("tenantId", "companyId");

-- CreateIndex
CREATE INDEX "Property_city_district_idx" ON "Property"("city", "district");

-- CreateIndex
CREATE INDEX "Property_latitude_longitude_idx" ON "Property"("latitude", "longitude");

-- CreateIndex
CREATE INDEX "Apartment_tenantId_companyId_idx" ON "Apartment"("tenantId", "companyId");

-- CreateIndex
CREATE INDEX "Apartment_propertyId_idx" ON "Apartment"("propertyId");

-- CreateIndex
CREATE INDEX "Apartment_status_idx" ON "Apartment"("status");

-- CreateIndex
CREATE INDEX "Apartment_unitNumber_idx" ON "Apartment"("unitNumber");

-- CreateIndex
CREATE UNIQUE INDEX "Apartment_propertyId_unitNumber_key" ON "Apartment"("propertyId", "unitNumber");

-- CreateIndex
CREATE INDEX "Tenant_tenantId_companyId_idx" ON "Tenant"("tenantId", "companyId");

-- CreateIndex
CREATE INDEX "Tenant_userId_idx" ON "Tenant"("userId");

-- CreateIndex
CREATE INDEX "Tenant_contactId_idx" ON "Tenant"("contactId");

-- CreateIndex
CREATE INDEX "Contract_tenantId_companyId_idx" ON "Contract"("tenantId", "companyId");

-- CreateIndex
CREATE INDEX "Contract_apartmentId_idx" ON "Contract"("apartmentId");

-- CreateIndex
CREATE INDEX "Contract_tenantRecordId_idx" ON "Contract"("tenantRecordId");

-- CreateIndex
CREATE INDEX "Contract_status_idx" ON "Contract"("status");

-- CreateIndex
CREATE INDEX "Contract_startDate_endDate_idx" ON "Contract"("startDate", "endDate");

-- CreateIndex
CREATE UNIQUE INDEX "Contract_tenantId_contractNumber_key" ON "Contract"("tenantId", "contractNumber");

-- CreateIndex
CREATE INDEX "Payment_tenantId_companyId_idx" ON "Payment"("tenantId", "companyId");

-- CreateIndex
CREATE INDEX "Payment_apartmentId_idx" ON "Payment"("apartmentId");

-- CreateIndex
CREATE INDEX "Payment_contractId_idx" ON "Payment"("contractId");

-- CreateIndex
CREATE INDEX "Payment_status_idx" ON "Payment"("status");

-- CreateIndex
CREATE INDEX "Payment_dueDate_idx" ON "Payment"("dueDate");

-- CreateIndex
CREATE INDEX "Payment_paidDate_idx" ON "Payment"("paidDate");

-- CreateIndex
CREATE INDEX "Appointment_tenantId_companyId_idx" ON "Appointment"("tenantId", "companyId");

-- CreateIndex
CREATE INDEX "Appointment_apartmentId_idx" ON "Appointment"("apartmentId");

-- CreateIndex
CREATE INDEX "Appointment_type_idx" ON "Appointment"("type");

-- CreateIndex
CREATE INDEX "Appointment_startDate_idx" ON "Appointment"("startDate");

-- CreateIndex
CREATE INDEX "Appointment_status_idx" ON "Appointment"("status");

-- CreateIndex
CREATE INDEX "RealEstateStaff_tenantId_companyId_idx" ON "RealEstateStaff"("tenantId", "companyId");

-- CreateIndex
CREATE INDEX "RealEstateStaff_userId_idx" ON "RealEstateStaff"("userId");

-- CreateIndex
CREATE INDEX "RealEstateStaff_staffType_idx" ON "RealEstateStaff"("staffType");

-- CreateIndex
CREATE INDEX "RealEstateStaff_role_idx" ON "RealEstateStaff"("role");

-- CreateIndex
CREATE UNIQUE INDEX "RealEstateStaff_tenantId_userId_key" ON "RealEstateStaff"("tenantId", "userId");

-- CreateIndex
CREATE INDEX "PropertyStaff_propertyId_idx" ON "PropertyStaff"("propertyId");

-- CreateIndex
CREATE INDEX "PropertyStaff_staffId_idx" ON "PropertyStaff"("staffId");

-- CreateIndex
CREATE UNIQUE INDEX "PropertyStaff_propertyId_staffId_key" ON "PropertyStaff"("propertyId", "staffId");

-- CreateIndex
CREATE INDEX "RealEstateMaintenanceRecord_tenantId_companyId_idx" ON "RealEstateMaintenanceRecord"("tenantId", "companyId");

-- CreateIndex
CREATE INDEX "RealEstateMaintenanceRecord_apartmentId_idx" ON "RealEstateMaintenanceRecord"("apartmentId");

-- CreateIndex
CREATE INDEX "RealEstateMaintenanceRecord_status_idx" ON "RealEstateMaintenanceRecord"("status");

-- CreateIndex
CREATE INDEX "RealEstateMaintenanceRecord_scheduledDate_idx" ON "RealEstateMaintenanceRecord"("scheduledDate");

-- CreateIndex
CREATE INDEX "EmailTemplate_tenantId_companyId_idx" ON "EmailTemplate"("tenantId", "companyId");

-- CreateIndex
CREATE INDEX "EmailTemplate_category_idx" ON "EmailTemplate"("category");

-- CreateIndex
CREATE UNIQUE INDEX "EmailTemplate_tenantId_name_key" ON "EmailTemplate"("tenantId", "name");

-- CreateIndex
CREATE INDEX "EmailCampaign_tenantId_companyId_idx" ON "EmailCampaign"("tenantId", "companyId");

-- CreateIndex
CREATE INDEX "EmailCampaign_templateId_idx" ON "EmailCampaign"("templateId");

-- CreateIndex
CREATE INDEX "EmailCampaign_apartmentId_idx" ON "EmailCampaign"("apartmentId");

-- CreateIndex
CREATE INDEX "EmailCampaign_status_idx" ON "EmailCampaign"("status");

-- CreateIndex
CREATE INDEX "AgreementReport_tenantId_companyId_idx" ON "AgreementReport"("tenantId", "companyId");

-- CreateIndex
CREATE INDEX "AgreementReport_appointmentId_idx" ON "AgreementReport"("appointmentId");

-- CreateIndex
CREATE INDEX "AgreementReport_apartmentId_idx" ON "AgreementReport"("apartmentId");

-- CreateIndex
CREATE INDEX "AgreementReport_type_idx" ON "AgreementReport"("type");

-- AddForeignKey
ALTER TABLE "Apartment" ADD CONSTRAINT "Apartment_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Contract" ADD CONSTRAINT "Contract_apartmentId_fkey" FOREIGN KEY ("apartmentId") REFERENCES "Apartment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Contract" ADD CONSTRAINT "Contract_tenantRecordId_fkey" FOREIGN KEY ("tenantRecordId") REFERENCES "Tenant"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_apartmentId_fkey" FOREIGN KEY ("apartmentId") REFERENCES "Apartment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Payment" ADD CONSTRAINT "Payment_contractId_fkey" FOREIGN KEY ("contractId") REFERENCES "Contract"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Appointment" ADD CONSTRAINT "Appointment_apartmentId_fkey" FOREIGN KEY ("apartmentId") REFERENCES "Apartment"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PropertyStaff" ADD CONSTRAINT "PropertyStaff_propertyId_fkey" FOREIGN KEY ("propertyId") REFERENCES "Property"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "PropertyStaff" ADD CONSTRAINT "PropertyStaff_staffId_fkey" FOREIGN KEY ("staffId") REFERENCES "RealEstateStaff"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "RealEstateMaintenanceRecord" ADD CONSTRAINT "RealEstateMaintenanceRecord_apartmentId_fkey" FOREIGN KEY ("apartmentId") REFERENCES "Apartment"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "EmailCampaign" ADD CONSTRAINT "EmailCampaign_templateId_fkey" FOREIGN KEY ("templateId") REFERENCES "EmailTemplate"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
